# Generated by Django 2.2.3 on 2019-07-24 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parapono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katanalotis', models.CharField(max_length=40)),
                ('etairia', models.CharField(max_length=60)),
                ('ypovoli', models.DateField(default=datetime.date.today)),
                ('prostimo', models.FloatField(blank=True)),
            ],
        ),
    ]
