# Generated by Django 2.2.3 on 2019-07-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_auto_20190724_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='parapono',
            name='armodios',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
