# Generated by Django 2.2.3 on 2019-07-24 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_parapono_armodios'),
    ]

    operations = [
        migrations.AddField(
            model_name='parapono',
            name='eisagogi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
