# Generated by Django 2.2.3 on 2019-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_parapono_eisagogi'),
    ]

    operations = [
        migrations.AddField(
            model_name='parapono',
            name='epitopios',
            field=models.BooleanField(default=False, verbose_name='Αρμόδιος'),
            preserve_default=False,
        ),
    ]
