# Generated by Django 2.2.3 on 2019-07-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0010_auto_20190730_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parapono',
            old_name='xristis',
            new_name='xristis1',
        ),
    ]
