# Generated by Django 2.2.3 on 2019-07-30 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0012_auto_20190730_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parapono',
            name='xristis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
