# Generated by Django 2.2.3 on 2019-07-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0013_auto_20190730_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parapono',
            name='xristis',
        ),
    ]
