# Generated by Django 2.2.3 on 2019-07-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0015_auto_20190730_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parapono',
            name='perigrafi',
        ),
        migrations.RemoveField(
            model_name='parapono',
            name='xristis',
        ),
        migrations.AddField(
            model_name='parapono',
            name='armodios',
            field=models.CharField(default='admin', max_length=20, verbose_name='Αρμόδιος'),
        ),
    ]
