# Generated by Django 2.2.3 on 2019-07-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0017_auto_20190730_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parapono',
            name='armodios',
            field=models.CharField(default='Φλώρου Νίκη', max_length=20, verbose_name='Αρμόδιος'),
        ),
        migrations.AlterField(
            model_name='parapono',
            name='perigrafi',
            field=models.TextField(default='', null=True, verbose_name='Περιγραφή'),
        ),
    ]
