# Generated by Django 2.2.3 on 2019-07-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0018_auto_20190730_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parapono',
            name='perigrafi',
            field=models.TextField(null=True, verbose_name='Περιγραφή'),
        ),
    ]
