# Generated by Django 2.2.3 on 2019-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0019_auto_20190730_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parapono',
            name='perigrafi',
            field=models.TextField(blank=True, null=True, verbose_name='Περιγραφή'),
        ),
    ]
