# Generated by Django 2.2.3 on 2019-07-31 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0020_auto_20190730_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parapono',
            name='epitopios',
            field=models.BooleanField(verbose_name='Επιτόπιος έλεγχος'),
        ),
        migrations.AlterField(
            model_name='parapono',
            name='prostimo',
            field=models.FloatField(blank=True, null=True, verbose_name='Επιβληθέν πρόστιμο'),
        ),
        migrations.AlterField(
            model_name='parapono',
            name='xristis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
    ]
