# Generated by Django 2.2.3 on 2019-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0021_auto_20190731_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parapono',
            name='prostimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Επιβληθέν πρόστιμο'),
        ),
    ]
